version: '2'

services:
  itest:
    build:
      context: docker/itest
      args:
         - KAFKA_VERSION
    links:
      - kafka
      - zookeeper
    volumes:
      - .:/work
    command: echo "dummy command"

  kafka:
    build:
      context: docker/kafka
      args:
         - KAFKA_VERSION
    expose:
      - "9092"
    links:
      - zookeeper

  zookeeper:
    build: docker/zookeeper
    expose:
      - "2181"
